In [11]:

import numpy as np

In [13]:
a=np.array([3,8,2,67,45])
a
print(a)

[ 3  8  2 67 45]


In [21]:
def show_array(arr):
    print('Array:',arr,sep='\n')
    print('type',type(arr))
    print('shape',arr.shape)
    print('Size',arr.size)
    print('Dtype',arr.dtype)

In [22]:
b=np.array([[10,11,13,14],[23,45,6,7],[4,6,43,4]])

In [23]:
show_array(b)

Array:
[[10 11 13 14]
 [23 45  6  7]
 [ 4  6 43  4]]
type <class 'numpy.ndarray'>
shape (3, 4)
Size 12
Dtype int32


In [26]:
c = np.array([[[10,100],[11,110],[13,130],[14,140]],
             [[45,145],[22,122],[9,19],[2,12]],
               [[6,16],[5,15],[1,11],[3,54]]])
print(c)
show_array(c)

[[[ 10 100]
  [ 11 110]
  [ 13 130]
  [ 14 140]]

 [[ 45 145]
  [ 22 122]
  [  9  19]
  [  2  12]]

 [[  6  16]
  [  5  15]
  [  1  11]
  [  3  54]]]
Array:
[[[ 10 100]
  [ 11 110]
  [ 13 130]
  [ 14 140]]

 [[ 45 145]
  [ 22 122]
  [  9  19]
  [  2  12]]

 [[  6  16]
  [  5  15]
  [  1  11]
  [  3  54]]]
type <class 'numpy.ndarray'>
shape (3, 4, 2)
Size 24
Dtype int32


In [27]:
b

array([[10, 11, 13, 14],
       [23, 45,  6,  7],
       [ 4,  6, 43,  4]])

In [43]:
b[0][0]
b[1][1:]
b[2][2:]
# subscripting [1st,2nd,3rd,.....,nth dim]
# subscripting [1st:1st end: stepsize,2nd,3rd,.....,nth dim]
b[0,0]
b[1,-3:]
b[:,-2]
b[:,-2:-1]

array([[13],
       [ 6],
       [43]])

In [78]:
b
b1=b[-1:,:]
print(b1.shape)
print(b1)

(1, 4)
[[ 4  6 43  4]]


In [83]:
#print(c)
print(c1=c[:1,:2,:1])
print(c2=c[:,1:2,:1])
print(c3=c[-2:,-1:,:1])
print(c4=c[:2,-2:,:])
print(c1.shape)



TypeError: 'c1' is an invalid keyword argument for print()

In [105]:
# Item assignment
b[1,2]=99

In [86]:
# item insertion
a=np.append(a,80)
a

array([ 3,  8,  2, 67, 45, 80, 80, 80])

In [88]:
np.append(b,[[9,90,900,9000]],axis=0)  # axis=0->row,  axis=1 -> columan

array([[  10,   11,   13,   14],
       [  23,   45,    6,    7],
       [   4,    6,   43,    4],
       [   9,   90,  900, 9000]])

In [89]:
np.append(b,[[9],[90],[900]],axis=1)

array([[ 10,  11,  13,  14,   9],
       [ 23,  45,   6,   7,  90],
       [  4,   6,  43,   4, 900]])

In [96]:
# deleting array
# del
b1=b.copy()
b1

array([[10, 11, 13, 14],
       [23, 45,  6,  7],
       [ 4,  6, 43,  4]])

In [97]:
np.delete(b1,0,axis=0)
b1


array([[10, 11, 13, 14],
       [23, 45,  6,  7],
       [ 4,  6, 43,  4]])

In [104]:
# Arthimatic operations
b1*2

array([[20, 22, 26, 28],
       [46, 90, 12, 14],
       [ 8, 12, 86,  8]])

In [100]:
# array Manipulation
#arr.reshape(....)
#arr.astype(....)


# More functiona to create array
# np.array()
#np.arange()  -> array version of range func, also allows float
# np.linspace() -> start ,end, no. of items
# np.ones()  -> generates all values as '1'
# np.zeros() -> all  values to zero
# np.random.random()
# np.random.randint()

In [103]:
np.ones((3,4),dtype='int')*5

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [101]:
b1.reshape(2,6,1,1)

array([[[[10]],

        [[11]],

        [[13]],

        [[14]],

        [[23]],

        [[45]]],


       [[[ 6]],

        [[ 7]],

        [[ 4]],

        [[ 6]],

        [[43]],

        [[ 4]]]])

In [102]:
b.astype(float)

array([[10., 11., 13., 14.],
       [23., 45.,  6.,  7.],
       [ 4.,  6., 43.,  4.]])